### ISSUE TITLE
Firefox Quantum Support?

### ISSUE THREAD

**Issue by K4YT3X** [alexanderby/darkreader#163]
The new firefox quantum has been released for quite a while.
**I really love this plugin** on chrome since it has been the most effective plugin to prevent my eyes from burning into balls of flames.

I saw requests in the past issues requesting a version for firefox, but never seen any signs of firefox version.
Since Firefox had a big refresh, can you please consider making a version for Firefox again?

I can't use Firefox without this plugin.

**Best,  
K4YT3X**

**Comment by alexanderby** [comment]
As soon as I finish refactoring I will publish it to Mozilla Addons again.

**Comment by K4YT3X** [comment]
@alexanderby Thanks a lot!

**Comment by rahuldroy** [comment]
is there anything I can do to help speed this up?

**Comment by alexanderby** [comment]
@rahuldroy Thanks for the suggestion. I'm still rewriting the CSS, will finish soon.

**Comment by alexanderby** [comment]
@rahuldroy Currently you can download and install the version, that didn't pass the Mozilla Team review http://shutov.by/darkreader/darkreader-3.5.0-firefox.zip

**Comment by rahuldroy** [comment]
why didn't it pass? I am happy to help out to speed this up if needed

**Comment by alexanderby** [comment]
One of the reasons were errors in console. I guess it happened for some restricted pages. You can help by determining which URLs should be ignored https://github.com/alexanderby/darkreader/blob/master/src/background/extension.ts#L244

**Comment by rahuldroy** [comment]
Perfect. I'll take a look at some other scripts and submit a PR. Leave this with me.

**Comment by eboracus** [comment]
Judging from the code there, the equivalent on Firefox should be `https://addons.mozilla.org/`. Which would make sense as it is restricted since FF57.

**Comment by K4YT3X** [comment]
@alexanderby Wow that was fast!
I can't just import it though since it has not been verified by mozilla.
Is there anything I can do to load it?
I don't know JS so is there anything I can help you with?

**Comment by alexanderby** [comment]
You can see how to install downloaded unsigned addon here https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox

**Comment by pshirshov** [comment]
Any update on this? I still would be happy to make a donation :)

**Comment by alexanderby** [comment]
I'm leaving my job in a few days and later will finish the required refactoring.

**Comment by alexanderby** [comment]
Done https://addons.mozilla.org/en-US/firefox/addon/darkreader/

**Comment by GithubUser5462** [comment]
Great job, thank you very much!
When you get the chance could you check/fix these two "bugs" if possible?

Firstly, when you view an image (right click, view image) it gets shifted to the top of the window.
Example: https://i.vimeocdn.com/portrait/58832_300x300

Secondly, it would be nice to have an option to white-list pdf files without having to white-list a domain.
Example: http://www.orimi.com/pdf-test.pdf
I remember that another similar addon had this option.

**Comment by RalphLesch** [comment]
For other image URLs (with file extensions), see #86 for a quick fix (excluding file extensions), although this does not fix your first example.
To exclude pdf files, just add pdf to the file extensions of the quick fix above: `...|pdf)$`

**Comment by pshirshov** [comment]
How may I donate, finally?..

**Comment by K4YT3X** [comment]
@alexanderby finally I don't have to be blinded by the screen. Than you so much!

**Comment by joshsleeper** [comment]
@alexanderby bump to close this issue. 👍

**Comment by wrikent3500** [comment]
![wtfhow2fix](https://user-images.githubusercontent.com/37148055/37096260-77ccd7f8-21ee-11e8-8670-ccea23b6d49d.GIF)
Anyone know what this is and how to fix it.....Firefox Quantum 58

**Comment by joshsleeper** [comment]
@wrikent3500 
if you think this is related to dark reader for some reason (which nothing in your image indicates), you should file a new issue instead of posting in a thread that's only tangentially related.

**Comment by K4YT3X** [comment]
@alexanderby Just check it out on Firefox and it works perfectly!
Thanks again for saving my eyes from the pure white backgrounds.

It might be time for me to close this issue.

**Best**,
K4YT3X

**Comment by alexanderby** [comment]
@pshirshov I've created a page at Open Collective https://opencollective.com/darkreader

**Comment by tjkirch** [comment]
Any chance of having PayPal/Amazon/etc. donation links?

**Comment by alexanderby** [comment]
@tjkirch Open Collective supports Stripe at the moment, but they are going to support PayPal too.

https://github.com/opencollective/opencollective/issues/365
https://github.com/opencollective/opencollective/issues/919
